//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictInfo()
        {
            this.EmplyeeBaiscInfoes = new HashSet<EmplyeeBaiscInfo>();
            this.OfficeInfoes = new HashSet<OfficeInfo>();
        }
    
        public int DisId { get; set; }
        public int DivisionId { get; set; }
        public string DisName { get; set; }
        public string DisCode { get; set; }
        public string DisDesc { get; set; }
    
        public virtual DivisionInfo DivisionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmplyeeBaiscInfo> EmplyeeBaiscInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeInfo> OfficeInfoes { get; set; }
    }
}
