//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplyeeBaiscInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmplyeeBaiscInfo()
        {
            this.LetterArchives = new HashSet<LetterArchive>();
            this.PostingInfoes = new HashSet<PostingInfo>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.PersonalLetterRecivers = new HashSet<PersonalLetterReciver>();
        }
    
        public System.Guid EmplyeeId { get; set; }
        public string EmplyeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeShortName { get; set; }
        public int GenderId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public int HomeDistrict { get; set; }
        public string ParmanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string EmpMobileNo { get; set; }
        public string EmpEmailAddress { get; set; }
        public string EmployeeImage { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public bool IsActiveEmp { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual DistrictInfo DistrictInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterArchive> LetterArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostingInfo> PostingInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalLetterReciver> PersonalLetterRecivers { get; set; }
    }
}
