//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsideOfficialReciver
    {
        public System.Guid IORId { get; set; }
        public System.Guid LetterArchiveId { get; set; }
        public int DId { get; set; }
        public int OfficeId { get; set; }
        public bool IORIsRead { get; set; }
        public Nullable<System.DateTime> IORREadDate { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual LetterArchive LetterArchive { get; set; }
        public virtual OfficeInfo OfficeInfo { get; set; }
    }
}
