//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterArchive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LetterArchive()
        {
            this.InsideOfficialRecivers = new HashSet<InsideOfficialReciver>();
            this.LetterAttachments = new HashSet<LetterAttachment>();
            this.OutsideLetterSends = new HashSet<OutsideLetterSend>();
            this.PersonalLetterRecivers = new HashSet<PersonalLetterReciver>();
        }
    
        public System.Guid LetterArchiveId { get; set; }
        public string LetterName { get; set; }
        public string LetterReferanceNo { get; set; }
        public int LetterTypeId { get; set; }
        public string LetterSubject { get; set; }
        public System.DateTime LetterDate { get; set; }
        public System.Guid CeatorId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorDesignationId { get; set; }
        public int CreatorOfficeId { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual EmplyeeBaiscInfo EmplyeeBaiscInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsideOfficialReciver> InsideOfficialRecivers { get; set; }
        public virtual LetterType LetterType { get; set; }
        public virtual OfficeInfo OfficeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterAttachment> LetterAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutsideLetterSend> OutsideLetterSends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalLetterReciver> PersonalLetterRecivers { get; set; }
    }
}
