//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficeInfo()
        {
            this.InsideOfficialRecivers = new HashSet<InsideOfficialReciver>();
            this.LetterArchives = new HashSet<LetterArchive>();
            this.PostingInfoes = new HashSet<PostingInfo>();
        }
    
        public int OfficeId { get; set; }
        public string OfficeCode { get; set; }
        public string OfficName { get; set; }
        public string OfficeSN { get; set; }
        public string OAdd1 { get; set; }
        public string OAdd2 { get; set; }
        public string OAdd3 { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public int OTId { get; set; }
        public string OPhoneNo { get; set; }
        public string OMobileNo { get; set; }
        public string OFaxNo { get; set; }
        public string Odesc { get; set; }
        public bool OfficeIsActive { get; set; }
        public Nullable<int> ParentOfficeId { get; set; }
    
        public virtual DistrictInfo DistrictInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsideOfficialReciver> InsideOfficialRecivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterArchive> LetterArchives { get; set; }
        public virtual OfficeType OfficeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostingInfo> PostingInfoes { get; set; }
    }
}
