//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeTypeWiseDesignation
    {
        public System.Guid OTWDId { get; set; }
        public int OTId { get; set; }
        public int DId { get; set; }
        public bool OTWDIsActive { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual OfficeType OfficeType { get; set; }
    }
}
