//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideLetterSend
    {
        public System.Guid OLSId { get; set; }
        public System.Guid LetterArchiveId { get; set; }
        public int OrgId { get; set; }
        public string OLSDesc { get; set; }
    
        public virtual LetterArchive LetterArchive { get; set; }
        public virtual OrganizationInfo OrganizationInfo { get; set; }
    }
}
