//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalLetterReciver
    {
        public System.Guid PLRId { get; set; }
        public System.Guid LetterArchiveId { get; set; }
        public System.Guid EmplyeeId { get; set; }
        public bool PLRIsRead { get; set; }
        public Nullable<System.DateTime> PLRReadDate { get; set; }
    
        public virtual EmplyeeBaiscInfo EmplyeeBaiscInfo { get; set; }
        public virtual LetterArchive LetterArchive { get; set; }
    }
}
