//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLOLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_OfficeInfoDetails
    {
        public int OfficeId { get; set; }
        public string OfficeCode { get; set; }
        public string OfficName { get; set; }
        public string OfficeSN { get; set; }
        public string OAdd1 { get; set; }
        public string OAdd2 { get; set; }
        public string OAdd3 { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public int OTId { get; set; }
        public string OTName { get; set; }
        public Nullable<int> ParentOfficeId { get; set; }
        public string ParentOfficeName { get; set; }
        public string OPhoneNo { get; set; }
        public string OMobileNo { get; set; }
        public string OFaxNo { get; set; }
        public string Odesc { get; set; }
        public bool OfficeIsActive { get; set; }
        public string DisName { get; set; }
    }
}
